### ISSUE TITLE
About the decoder

### ISSUE THREAD

**Issue by x09326** [floriandejonckheere/jsvm#3]
Hi, I'm doing an experiment.

I am trying to send the SVC encoded video to another host. My encoded video are three MGS quality layers, which means D=0, T=0, Q=2.

For example, there are three frames, frame 1, frame 2 and frame 3. 
I found that if I drop the Q1 and Q2 of frame 1, then drop all frame 2 and frame 3, the decoder will shutdown when decode to frame 1.

Could you help me figure out this problem? 

The important parameters of the encode file are below:
GOP SIZE =1
IntraPeriod =1
IDRPeriod =1
 
Because I want the frame 1 packet drop, then it will not affect the PSNR of others frame, so I want all pictures are I picture.

If the information is not enough, please let me know.
I want to know how to make the video work, or know why it can not work

Please help me figure out this, thanks.

**Comment by floriandejonckheere** [comment]
Hi

I originally set up this repo to have a git mirror of the CVS repo. I am not the maintainer of this software, nor do I have any ties to the people who wrote it. Since the CVS repo disappeared, this git repo exists simply for archival purposes and is not maintained.
I'm afraid I cannot help with any technical problems you might have.

Regards

Florian
